import React, { useEffect } from 'react'
import Drawer from './Drawer'
import Toolbar from './Toolbar'
import styles from '../../styles/Layout.module.scss'
import Head from 'next/head'
import LoginDialog from '../LoginModal'
import useAuthService from '../../hooks/apollo/useAuthService'

export default function Layout({ children }: { children: React.ReactNode }) {
  const { checkAuth } = useAuthService()

  useEffect(() => {
    checkAuth()
  }, [])

  return (
    <main className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Drawer />
      <Toolbar />
      <div className={styles.container}>{children}</div>
      <LoginDialog />
    </main>
  )
}
